# -*- coding: utf-8 -*-
"""#step_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gg5NhKYKxZDr8MyUhCpaaGv3u9CUa_ah
"""

#1

print('Hello World!')

#2

print('강한친구 대한육군')
print('강한친구 대한육군')

#3

print('''\\    /\\
 )  ( ')
(  /  )
 \\(__)|''')

print('\\    /\\')
print(") )  ( ')")
print('(  /  )')
print(' \\(__)|')

#4

print('''|\\_/|
|q p|   /}
( 0 )"""\\
|"^"`    |
||_/=\\\\__|''')